# Generated by Django 4.0.6 on 2022-09-05 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id_chofer', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(default='', max_length=100, verbose_name='Nombre Completo')),
                ('cedula', models.CharField(default=None, max_length=30, unique=True, verbose_name='Cedula')),
                ('edad', models.PositiveSmallIntegerField(default=18, verbose_name='Edad')),
                ('numero_telefono', models.CharField(default=None, max_length=20, unique=True, verbose_name='Número de Telefono')),
                ('direccion_particular', models.CharField(default='Somewhere', max_length=150, verbose_name='Reside en')),
                ('email', models.EmailField(blank=True, default='SomeOne@gamil.com', max_length=254, null=True, unique=True)),
                ('nivel_escolar', models.CharField(choices=[('Inicial', 'Inicial'), ('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Superior', 'Superior')], max_length=10, verbose_name='Cual es su nivel escolar?')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default=None, max_length=10, verbose_name='Elija un Sexo')),
                ('agnos_experiencia', models.PositiveSmallIntegerField(default=0, verbose_name='Cuantos años de experiencia tiene?')),
                ('cantidad_de_multas', models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad de Multas')),
                ('cantidad_viajes', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Cantidad de Vaijes Realizados')),
                ('clasificacion', models.CharField(choices=[('A', 'A'), ('B', 'B')], default=None, max_length=1, verbose_name='Clasificación de Tipo')),
            ],
            options={
                'db_table': 'Coferes',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(default=None, max_length=7, unique=True)),
                ('marca', models.CharField(default=None, max_length=100)),
                ('peso_en_toneladas', models.DecimalField(decimal_places=2, default=None, max_digits=5, verbose_name='Peso en Toneladas')),
                ('tipo_de_comnustible', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Diesel', 'Diesel'), ('Petroleo', 'Petroleo')], default=None, max_length=8, verbose_name='Tipo de Combustible')),
                ('kms_recorridos', models.PositiveIntegerField(default=0, verbose_name='Kilometros Recorridos')),
                ('velocidad_maxima', models.PositiveSmallIntegerField(default=0, verbose_name='Velocidad Máxima (km/h)')),
                ('agnos_explotacion', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Años de Explotación')),
                ('cantidad_viajes', models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Cantidad de Vaijes Realizados')),
                ('tipo_servicio', models.CharField(choices=[('Regular', 'Regular'), ('Especial', 'Especial'), ('VIP', 'VIP')], default=None, max_length=8, verbose_name='Tipo de Servicio')),
                ('climatizacion', models.BooleanField(default=None, verbose_name='Tiene aire acondicionado?')),
                ('cantidad_asientos', models.IntegerField(default=None, verbose_name='Cuantos asientos tiene?')),
                ('disponibilidad', models.BooleanField(default=None, verbose_name='Está disponible?')),
            ],
            options={
                'db_table': 'Vehiculos',
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_viaje', models.CharField(choices=[('Local', 'Local'), ('Municipal', 'Municipla'), ('Provincial', 'Provincial'), ('Turismo', 'Turismo'), ('Arrendado', 'Arrendado')], max_length=10, verbose_name='Tipo de Viaje')),
                ('inicio_viaje', models.DateTimeField(default=None, verbose_name='Inicio del Viaje')),
                ('fin_viaje', models.DateTimeField(default=None, verbose_name='Fin del Viaje')),
                ('kms_recorridos', models.PositiveIntegerField(default=0, verbose_name='Kilometros Recorridos en el Viaje')),
                ('comentarios', models.TextField(default='...', verbose_name='Haga un Comentario')),
                ('estado_viaje', models.CharField(choices=[('Creado', 'Creado'), ('En Proceso', 'En Proceso'), ('Cerrado', 'Cerrado')], default='Creado', max_length=10, verbose_name='Estado del Viaje')),
                ('costo_usd', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Costo del viaje en USD$')),
                ('chofer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_vehiculos_api.chofer')),
                ('vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_vehiculos_api.vehiculo')),
            ],
            options={
                'db_table': 'Viajes',
            },
        ),
    ]
