# Generated by Django 4.0.6 on 2022-09-06 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0002_rename_user_name_sgvuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sgvuser',
            old_name='id_user',
            new_name='id',
        ),
    ]
